(WIN_COMBINATIONS).to include_array([0, 1, 2])
(WIN_COMBINATIONS).to include_array([3, 4, 5])
(WIN_COMBINATIONS).to include_array([6, 7, 8])
(WIN_COMBINATIONS).to include_array([0, 3, 6])
(WIN_COMBINATIONS).to include_array([1, 4, 7])
(WIN_COMBINATIONS).to include_array([2, 5, 8])
(WIN_COMBINATIONS).to include_array([0, 4, 8])
(WIN_COMBINATIONS).to include_array([6, 4, 2])